# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.
ifeq ($(config),debug)
override config := Debug
endif
ifeq ($(config),release)
override config := Release
endif
ifeq ($(config),Debug)
CPPFLAGS ?= -DDEBUG
CFLAGS ?= -g -O0
CXXFLAGS ?= -g -O0
LDFLAGS ?= -g
else ifeq ($(config),Release)
CPPFLAGS ?= -DNDEBUG 
CFLAGS ?= -O2
CXXFLAGS ?= -O2
else ifneq (,$(config))
$(warning Unknown configuration "$(config)")
endif

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := g++
CXX := g++

CPPFLAGS = -std=c++14

# The directory for the build files, may be overridden on make command line.
builddir = .

all: $(builddir)/test

$(builddir)/test: $(builddir)/test_LightsControl.o $(builddir)/test_hangman.o $(builddir)/test_HangmanGame.o $(builddir)/test_HangmanWidget.o $(builddir)/test_HighScoresWidget.o $(builddir)/test_ImagesWidget.o $(builddir)/test_Session.o $(builddir)/test_User.o
	$(CXX) -o $@ $(LDFLAGS) $(builddir)/test_LightsControl.o $(builddir)/test_hangman.o $(builddir)/test_HangmanGame.o $(builddir)/test_HangmanWidget.o $(builddir)/test_HighScoresWidget.o $(builddir)/test_ImagesWidget.o $(builddir)/test_Session.o $(builddir)/test_User.o -lwt -lwthttp -lboost_system -lwtdbo -lwtdbosqlite3 -lcrypt -pthread

$(builddir)/test_hangman.o: hangman.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread hangman.c

$(builddir)/test_HangmanGame.o: HangmanGame.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread HangmanGame.c

$(builddir)/test_HangmanWidget.o: HangmanWidget.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread HangmanWidget.c

$(builddir)/test_HighScoresWidget.o: HighScoresWidget.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread HighScoresWidget.c

$(builddir)/test_ImagesWidget.o: ImagesWidget.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread ImagesWidget.c

$(builddir)/test_Session.o: Session.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread Session.c

$(builddir)/test_User.o: User.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread User.c

$(builddir)/test_LightsControl.o: LightsControl.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread LightsControl.c 

clean:
	rm -f *.o
	rm -f *.d
	rm -f $(builddir)/test

.PHONY: all clean

# Dependencies tracking:
-include *.d
